[package]
description = "Status Page for Parity"
name = "parity-status"
version = "0.3.4"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]

[dependencies]
parity-webapp = { git = "https://github.com/tomusdrw/parity-webapp.git" }
